name: Go Test Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: project-sem-1
          POSTGRES_USER: validator
          POSTGRES_PASSWORD: val1dat0r
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Make scripts executable
      run: |
        chmod +x scripts/prepare.sh
        chmod +x scripts/run.sh
        chmod +x scripts/tests.sh

    - name: Prepare PostgreSQL Environment
      run: ./scripts/prepare.sh
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: project-sem-1
        POSTGRES_USER: validator
        POSTGRES_PASSWORD: val1dat0r

    - name: Run application
      run: ./scripts/run.sh
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: project-sem-1
        POSTGRES_USER: validator
        POSTGRES_PASSWORD: val1dat0r

    - name: Run Tests
      run: ./scripts/tests.sh 1
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: project-sem-1
        POSTGRES_USER: validator
        POSTGRES_PASSWORD: val1dat0r